CREATE TABLE IF NOT EXISTS JOB_COUNT (
    JOB_ID INT AUTO_INCREMENT PRIMARY KEY,
    NODE VARCHAR(10),
    JOB_NAME VARCHAR(20),
    LOG_DATE DATE,
    MATCH_COUNT INT,
    CREATE_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
